name: Keep Streamlit App Awake

on:
  schedule:
    # Runs at 00:00 UTC every 3 days
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run this manually anytime

jobs:
  ping-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Keep Alive Action
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        echo "Last pinged on: $(date)" > ping.txt
        git add ping.txt
        git commit -m "chore: automated ping to keep app awake" || exit 0
        git push
